import globals from 'globals';

// Catatan: test.js TIDAK di-ignore — espree 10 (eslint 9) sudah mendukung import attributes (ES2025).
export default [
	{
		ignores: [
			'lib/lowdb/index.js',
		],
	},
	{
		files: ['**/*.js'],
		languageOptions: {
			// ecmaVersion 2025 = maksimum yang didukung espree 10 (eslint 9)
			ecmaVersion: 2025,
			sourceType: 'module',
			globals: {
				...globals.node,
				...globals.es2021,
				global: 'readonly',
				wait: 'readonly',
				eror: 'readonly',
				btc: 'readonly',
				lann: 'readonly',
				globalThis: 'readonly',
				db: 'writable',
				wm: 'readonly',
				packname: 'readonly',
				author: 'readonly',
				opts: 'readonly',
				plugins: 'readonly',
				Bgardenboxs: 'writable',
				robot: 'writable',
				usedPrefix: 'readonly',
				owner: 'readonly',
				numberowner: 'readonly',
				stiker_wait: 'readonly',
				aksesKey: 'readonly',
				thumb: 'readonly',
				ownernya: 'readonly',
				MessageType: 'readonly',
				DevMode: 'readonly',
				dbPath: 'readonly',
				options: 'readonly',
				APIKeys: 'readonly',
				conn: 'readonly',
				e: 'readonly',
				fs: 'readonly',
				admins: 'readonly',
				days: 'readonly',
				hours: 'readonly',
				nameowner: 'readonly',
				mail: 'readonly',
				instagram: 'readonly',
				gc: 'readonly',
				st2: 'readonly',
				fverif: 'readonly',
				hrobo: 'readonly',
				hrhinoceros: 'readonly',
				hlion: 'readonly',
				hkyubi: 'readonly',
				hhorse: 'readonly',
				hgriffin: 'readonly',
				hdragon: 'readonly',
				hcentaur: 'readonly',
				m: 'readonly',
				loadDatabase: 'readonly',
				spins: 'readonly',
				localStorage: 'readonly',
				nullish: 'readonly',
				messageType: 'readonly',
				pase: 'readonly',
				row3: 'readonly',
				button3: 'readonly',
				trueFileName: 'readonly',
				axios: 'readonly',
				fileTypeFromBuffer: 'readonly',
				util: 'readonly',
				cusor: 'readonly',
			},
		},
		rules: {
			'no-undef': 'error',
			'no-unexpected-multiline': 'error',
			// Pola lama `if ((x = ...))` dengan paren disengaja di banyak plugin → pakai default except-parens
			'no-cond-assign': ['error', 'except-parens'],
			'no-const-assign': 'error',
			'no-dupe-args': 'error',
			'no-dupe-class-members': 'error',
			'no-dupe-keys': 'error',
			'no-duplicate-case': 'error',
			'no-empty-pattern': 'error',
			'no-func-assign': 'error',
			'no-import-assign': 'error',
			'no-new-native-nonconstructor': 'error',
			'no-obj-calls': 'error',
			'no-unreachable': 'error',
			'no-unreachable-loop': 'error',
			'no-unsafe-finally': 'error',
			'no-unsafe-negation': 'error',
			'no-unused-private-class-members': 'error',
			'no-constant-condition': ['error', { checkLoops: false }],
			// no-redeclare off: pola legacy `var stiker` berulang di else-if chain (40+ tempat) — legal di JS
			'no-redeclare': 'off',
			'no-control-regex': 'off',
			'no-empty': ['error', { allowEmptyCatch: true }],
			'no-fallthrough': 'off',
			'no-useless-escape': 'off',
			'no-async-promise-executor': 'off',
		},
	},
	{
		// kode obfuscated (anti-copas) — assignment ke fungsi itu disengaja
		files: ['plugins/info-tqto.js'],
		rules: {
			'no-func-assign': 'off',
		},
	},
	{
		// return di dalam finally untuk early-exit info grup — pola lama, sengaja
		files: ['plugins/group-info.js'],
		rules: {
			'no-unsafe-finally': 'off',
		},
	},
];
